{% set name = "libebm" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/interpretml/interpret/archive/979d93f72cab2e6206114ca8d46f54b308a2cba2.tar.gz
  sha256: db00cbc1b940682749b0cf6bcd1f8650eb6a095d32f15e229ee23de66918083e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libebm', max_pin='x.x.x') }}
  script: .\build.bat -conda && copy .\bld\lib\libebm_win_x64.dll "%LIBRARY_BIN%\libebm.dll"  # [win]
  script: /bin/sh ./build.sh -conda && cp ./bld/lib/libebm.so "$PREFIX/lib/libebm.so"  # [linux]
  script: /bin/sh ./build.sh -conda && cp ./bld/lib/libebm.dylib "$PREFIX/lib/libebm.dylib"  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}

test:
  commands:
    - where libebm.dll  # [win]
    # IF NOT EXIST "%LIBRARY_BIN%\libebm.dll" EXIT /B 1  # [win]
    - test -f $PREFIX/lib/libebm.so       # [linux]
    - test -f $PREFIX/lib/libebm.dylib     # [osx]

about:
  home: https://github.com/interpretml/interpret
  summary: Fit interpretable models. Explain blackbox machine learning.
  description: |
    Shared library for the interpret package.

    https://github.com/interpretml/interpret
  license: MIT
  license_file: LICENSE
  doc_url: https://interpret.ml/docs
  dev_url: https://interpret.ml/docs/installation-guide.html

extra:
  recipe-maintainers:
    - paulbkoch
    - interpret-ml
