{% set name = "libebm" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/interpretml/interpret/archive/9a6ccf0062c57606d9ad853502b81ac9ebf87028.tar.gz
  sha256: 1b1dc21e372c1f7a5cec04c457eee90f44de39b050aa90fe99df3711aefbc07a

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libebm', max_pin='x.x.x') }}
  script: .\build.bat && copy .\staging\libebm_win_x64.dll "%LIBRARY_BIN%\libebm.dll"  # [win]
  script: /bin/sh ./build.sh && cp ./python/interpret-core/interpret/lib/libebm_linux_x64.so "$PREFIX/lib/libebm.so"  # [linux]
  script: /bin/sh ./build.sh && cp ./python/interpret-core/interpret/lib/libebm_mac_x64.dylib "$PREFIX/lib/libebm.dylib"  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - where libebm.dll  # [win]
    # IF NOT EXIST "%LIBRARY_BIN%\libebm.dll" EXIT /B 1  # [win]
    - test -f $PREFIX/lib/libebm.so       # [linux]
    - test -f $PREFIX/lib/libebm.dylib     # [osx]

about:
  home: https://github.com/interpretml/interpret
  summary: Fit interpretable machine learning models. Explain blackbox machine learning.
  description: |
    Shared library for the interpret package.

    https://github.com/interpretml/interpret
  license: MIT
  license_file: LICENSE
  doc_url: https://interpret.ml/docs/getting-started
  dev_url: https://interpret.ml/docs/installation-guide.html

extra:
  recipe-maintainers:
    - paulbkoch
    - interpret-ml
