{% set name = "libebm" %}
{% set version = "0.6.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/interpretml/interpret/archive/099a1010fae7289e8d3b2aa951ede0dbc596fba9.tar.gz
  sha256: c36b71bbb7c78517f0edc97e94934d672fcfdfd4c9c1ad3280b1c4b96e550d88

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libebm', max_pin='x.x.x') }}
  script: .\build.bat -conda && copy .\bld\lib\libebm_win_x64.dll "%LIBRARY_BIN%\libebm.dll"  # [win]
  script: /bin/sh ./build.sh -conda && cp ./bld/lib/libebm.so "$PREFIX/lib/libebm.so"  # [linux]
  script: /bin/sh ./build.sh -conda && cp ./bld/lib/libebm.dylib "$PREFIX/lib/libebm.dylib"  # [osx]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

test:
  commands:
    - where libebm.dll  # [win]
    # IF NOT EXIST "%LIBRARY_BIN%\libebm.dll" EXIT /B 1  # [win]
    - test -f $PREFIX/lib/libebm.so       # [linux]
    - test -f $PREFIX/lib/libebm.dylib     # [osx]

about:
  home: https://github.com/interpretml/interpret
  summary: Fit interpretable models. Explain blackbox machine learning.
  description: |
    Shared library for the interpret package.

    https://github.com/interpretml/interpret
  license: MIT
  license_file: LICENSE
  doc_url: https://interpret.ml/docs
  dev_url: https://interpret.ml/docs/installation-guide.html

extra:
  recipe-maintainers:
    - paulbkoch
    - interpret-ml
