{% set name = "libebm" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/interpretml/interpret/archive/200f9c3f08da6f17bdbeaee0e3285a2458f92f18.tar.gz
  # curl -sL https://github.com/interpretml/interpret/archive/200f9c3f08da6f17bdbeaee0e3285a2458f92f18.tar.gz | openssl sha256
  sha256: e61f014fb24f0dae58e4099f6affd15713928e66eab5078892e546b704920b8b
  # url: https://github.com/interpretml/interpret/archive/v{{ version }}.tar.gz

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libebm', max_pin='x.x.x') }}
  script: .\build.bat && copy .\staging\lib_ebm_native_win_x64.dll "%LIBRARY_BIN%\libebm.dll"  # [win]
  script: /bin/sh ./build.sh && cp ./python/interpret-core/interpret/lib/lib_ebm_native_linux_x64.so "$PREFIX/lib/libebm.so"  # [linux]
  script: /bin/sh ./build.sh && cp ./python/interpret-core/interpret/lib/lib_ebm_native_mac_x64.dylib "$PREFIX/lib/libebm.dylib"  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - if not exist %LIBRARY_BIN%\libebm.dll exit 1  # [win]
    - test -f $PREFIX/lib/libebm.so       # [linux]
    - test -f $PREFIX/lib/libebm.dylib     # [osx]

about:
  home: https://github.com/interpretml/interpret
  summary: Fit interpretable machine learning models. Explain blackbox machine learning.
  description: |
    Shared library for **the** interpret package.

    https://github.com/interpretml/interpret
  license: MIT
  license_file: LICENSE
  doc_url: https://interpret.ml/docs/getting-started
  dev_url: https://interpret.ml/docs/installation-guide.html

extra:
  recipe-maintainers:
    - paulbkoch
